ops/installation/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
    url(r'^post_server_info/',views.post_server_info,name='post_server_info'),
    url(r'^servers/$',views.server,name='server'),
    url(r'^servers/init/',views.init,name='init'),
    url(r'^servers/install/',views.install,name='install'),
    url(r'^server/detail/(\w+)/$',views.server_detail,name='server_detail'),
    url(r'^server/delete/',views.server_delete,name='server_delete'),
    url(r'^server/edit/(\w+)/$',views.server_edit,name='server_edit'),
    url(r'^server/raid/(\w+)/(\w+)/(\w*)',views.server_raid,name='server_raid'),
    url(r'^select_cab/',views.select_cab,name='select_cab'),
    url(r'^server/status/',views.server_change_status,name='server_change_status'),
    url(r'^server/ipmi/(\w+)/(\w+)/$',views.server_ipmi,name='server_ipmi'),
    url(r'^server/ipmi/(\w+)/$',views.update_ipmi,name='update_ipmi'),
    url(r'^install_pre_post/$',views.install_pre_post,name='install_pre_post'),
    url(r'^server/install/(\w+)/$',views.get_system,name='get_system'),
    url(r'^server/add_system/(\w+)/$',views.add_system,name='add_system'),
    url(r'^server/edit_system/(\w+)/(\w+)/$',views.edit_system,name='edit_system'),
    url(r'^server/system/view/(\w+)/$',views.view_system,name='view_system'),
    url(r'^server/system/delete/(\w+)/(\w+)/$',views.delete_system,name='delete_system'),
    url(r'^celery/$',views.tasks,name='tasks'),
    url(r'^vm/vcenter/$',views.vcenter,name='vcenter'),
    url(r'^vm/add_vcenter/$',views.add_vcenter,name='add_vcenter'),
    url(r'^vm/edit_vcenter/(\d+)/$',views.edit_vcenter,name='edit_vcenter'),
    url(r'^vm/delete_vcenter/(\d+)/$',views.delete_vcenter,name='delete_vcenter'),
    url(r'^vm/add_vm/$',views.add_vm,name='add_vm'),
    url(r'^vm/get_obj',views.get_obj,name='get_obj'),
    url(r'^installserver/$',views.cobbler,name='cobbler'),
    url(r'^installserver/add/$',views.add_cobbler,name='add_cobbler'),
    url(r'^installserver/edit/(\d+)/$',views.edit_cobbler,name='edit_cobbler'),
]

ops/ops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$',views.base,name="base"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),    
	url(r'^accounts/login',views.login,name="login"),
	url(r'^logout/',views.logout,name="logout"),
    url(r'^users/',include('users.urls',namespace='users')),  
    url(r'^installation/',include('installation.urls',namespace='installation')),
    url(r'^opsdb/',include('opsdb.urls',namespace='opsdb')),
    url(r'^cronjob/',include('cronjob.urls',namespace='cronjob')),
]

ops/opsdb/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
	url(r'^systems/$',views.systems,name='systems'),
    url(r'^systems/show/(.+)/$',views.system,name='system'),
	url(r'^systems/add/$',views.add_system,name='add_system'),
    url(r'^systems/edit/(.+)/$',views.edit_system,name='edit_system'),
    url(r'^systems/delete/$',views.delete_system,name='delete_system'),
    url(r'^systems/remote_run/$',views.salt_run,name='salt_run'),
    url(r'^systems/state_deploy/$',views.salt_state,name='salt_state'),
    url(r'^systems/state_manage/$',views.state_manage,name='state_manage'),
    url(r'^systems/state_upload/$',views.state_upload,name='state_upload'),
    url(r'^systems/state_delete/$',views.state_delete,name='state_delete'),
    url(r'^systems/minion_key/(\w+)/$',views.minion_key,name='minion_key'),
    url(r'^systems/act_key/$',views.act_key,name='act_key'),
    url(r'^systems/saltjoblist/$',views.saltjoblist,name='saltjoblist'),
    url(r'^systems/job_cjid/(\d*)/$',views.job_cjid,name='job_cjid'),
    url(r'^systems/job_jid/(\d*)/$',views.job_jid,name='job_jid'),
    url(r'^systems/kill_job/(\d+)/$',views.kill_job,name='kill_job'),
    url(r'^systems/kill_job/(\d+)/$',views.kill_job,name='kill_job'),
    url(r'^hostgroup/grouplist/$',views.grouplist,name='grouplist'),
    url(r'^hostgroup/add/$',views.add_hostgroup,name='add_hostgroup'),
    url(r'^hostgroup/edit/(\d+)/$',views.edit_hostgroup,name='edit_hostgroup'),
    url(r'^hostgroup/delete/$',views.delete_hostgroup,name='delete_hostgroup'),
    url(r'^environment/envlist/$',views.envlist,name='envlist'),
    url(r'^environment/add_env/$',views.add_env,name='add_env'),
    url(r'^environment/edit_env/(\d+)/$',views.edit_env,name='edit_env'),
    url(r'^environment/delete/$',views.delete_env,name='delete_env'),
    url(r'^business/busilist/$',views.busilist,name='busilist'),
    url(r'^business/add_busi/$',views.add_busi,name='add_busi'),
    url(r'^business/edit_busi/(\d+)/$',views.edit_busi,name='edit_busi'),
    url(r'^business/delete/$',views.delete_busi,name='delete_busi'),
    url(r'^application/applist/$',views.applist,name='applist'),
    url(r'^application/add_app/$',views.add_app,name='add_app'),
    url(r'^application/edit_app/(\d+)/$',views.edit_app,name='edit_app'),
    url(r'^application/delete/$',views.delete_app,name='delete_app'),
]

ops/opsdb/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,redirect
from django.shortcuts import HttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from .models import *
from ops.sshapi import remote_cmd,put_file
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from json2html import *
from .saltapi import SaltAPI
import os
import time
from django.contrib.auth.decorators import login_required
from users.custom_decorators import role_required
from django.contrib.auth.models import User,Group
from installation.models import Environment

# connect mongodb
try:
	from pymongo import MongoClient
	salt_mongo = get_object_or_404(ServiceHost,service='salt_mongo')
	client = MongoClient(salt_mongo.ip,int(salt_mongo.port))
	mongo_salt = client.salt 
except Exception as e:
	# raise e
	pass

def systems(request):
	system_list = System.objects.select_related().filter(is_delete=False)
	page_number =  request.GET.get('page_number')
	if page_number:
	    page_number = int(page_number)
	else:
	    page_number =  10
	paginator = Paginator(system_list, page_number)
	page = request.GET.get('page')
	try:
	    systems = paginator.page(page)
	except PageNotAnInteger:
	    # If page is not an integer, deliver first page.
	    systems = paginator.page(1)
	except EmptyPage:
	    # If page is out of range (e.g. 9999), deliver last page of results.
	    systems = paginator.page(paginator.num_pages)
	return render(request,'opsdb/host/systems.html',locals())


def system(request,id):
	system = mongo_salt.salt_grains.find_one({'id':id})
	if system:
		system_detail = json2html.convert(json = system['return'])
	else:
		system_detail = '抱歉,未查询到当前主机信息'
	return HttpResponse(system_detail)



@login_required
@role_required('hostadmin','admin')
@csrf_exempt
def add_system(request):
	if request.method == "GET":
		return render(request,'opsdb/host/add_system.html')
	else:
		ip = request.POST.get('ip','')
		port = request.POST.get('port','')
		username = request.POST.get('username','')
		password = request.POST.get('password','')
		if ip and port and username and password:
			cmd = "curl -L http://192.168.3.166/cobbler/svc/install-minion.sh | sh"
			ret = remote_cmd(cmd,ip,port=int(port),user=username,passwd=password)
			if ret['status'] and not ret['err']:
				messages.success(request, '添加成功')
			else:
				messages.error(request, ret['result'])
		return render(request,'opsdb/host/add_system.html',locals())

@login_required
@role_required('hostadmin','admin')
@csrf_exempt
def edit_system(request,id):
	hostgroups = HostGroup.objects.all()
	apps = Application.objects.all()
	system = get_object_or_404(System,pk=id)
	if request.method == "GET":
		return render(request,'opsdb/host/edit_system.html',locals())
	else:
		hostgroup_list = request.POST.getlist('hostgroups','')
		app_list = request.POST.getlist('apps','')
		try:
			system.hostgroups = hostgroup_list
			system.applications = app_list
			result = {'status':True,'msg':'变更成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		return render(request,'opsdb/host/edit_system.html',locals())

@login_required
@role_required('hostadmin','admin')
@csrf_exempt
def delete_system(request):
	target = request.POST.get('ids[]','')
	salt_master = get_object_or_404(ServiceHost,service='salt_api')
	salt = SaltAPI(salt_master.ip,salt_master.user,salt_master.password,port=salt_master.port)
	ret = {}
	for tgt in target:
		try:
			salt.key(client='wheel',fun='key.delete',match=tgt)
			System.objects.filter(pk=tgt).update(is_delete=True)
		except Exception as e:
			ret[tgt] = str(e)
	return HttpResponse(ret)

@login_required
@role_required('hostadmin','admin')
def grouplist(request):
	group_list = HostGroup.objects.all()
	page_number =  request.GET.get('page_number')
	if page_number:
	    page_number = int(page_number)
	else:
	    page_number =  10
	paginator = Paginator(group_list, page_number)
	page = request.GET.get('page')
	try:
	    hostgroups = paginator.page(page)
	except PageNotAnInteger:
	    # If page is not an integer, deliver first page.
	    hostgroups = paginator.page(1)
	except EmptyPage:
	    # If page is out of range (e.g. 9999), deliver last page of results.
	    hostgroups = paginator.page(paginator.num_pages)
	return render(request,'opsdb/host/grouplist.html',locals())

@login_required
@role_required('hostadmin','admin')
def add_hostgroup(request):
	systems = System.objects.select_related().filter(is_delete=False)
	groups = Group.objects.all()
	if request.method == "GET":
		return render(request, 'opsdb/host/add_hostgroup.html',locals())
	else:
		name = request.POST.get('name','')
		systems_list = request.POST.getlist('systems','')
		groups_list = request.POST.getlist('groups','')
		comment = request.POST.get('comment','')
		try:
			hostgroup,created = HostGroup.objects.get_or_create(name=name)
			if created:
				hostgroup.groups = groups_list
				hostgroup.system_set = systems_list
				if comment:
					hostgroup.comment = comment
					hostgroup.save()
			result = {'status':True,'msg':'添加成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		return render(request, 'opsdb/host/add_hostgroup.html',locals())

@login_required
@role_required('hostadmin','admin')
def edit_hostgroup(request,id):
	systems = System.objects.select_related().filter(is_delete=False)
	groups = Group.objects.all()
	hostgroup = HostGroup.objects.get(pk=id)
	if request.method == "GET":
		return render(request, 'opsdb/host/edit_hostgroup.html',locals())
	else:
		name = request.POST.get('name','')
		systems_list = request.POST.getlist('systems','')
		groups_list = request.POST.getlist('groups','')
		comment = request.POST.get('comment','')
		try:
			if name != hostgroup.name:
				hostgroup.name = name
			if comment != hostgroup.comment:
				hostgroup.comment = comment
			hostgroup.system_set = systems_list
			hostgroup.groups = groups_list
			hostgroup.save()
			result = {'status':True,'msg':'更新成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		hostgroup = HostGroup.objects.get(pk=id)
		return render(request, 'opsdb/host/edit_hostgroup.html',locals())

@login_required
@role_required('hostadmin','admin')
@csrf_exempt
def delete_hostgroup(request):
	ids = request.POST.getlist('ids[]','')
	result = {}
	for group_id in ids:
		try:
			HostGroup.objects.filter(pk=group_id).delete()
		except Exception as e:
			result[group_id] = str(e)
	return HttpResponse(json.dumps(result))


@login_required
@role_required('salt','admin')
def salt_run(request):
	salt_funs = SaltFun.objects.all()
	if request.method == 'GET':
		pass
	else:
		user = request.user.username
		if request.META.has_key('HTTP_X_FORWARDED_FOR'):
			client =  request.META['HTTP_X_FORWARDED_FOR']  
		else:
			client = request.META['REMOTE_ADDR']
		salt_master = get_object_or_404(ServiceHost,service='salt_api')
		salt = SaltAPI(salt_master.ip,salt_master.user,salt_master.password,port=salt_master.port)
		try:
			fun = request.POST.get('fun','')
			arg_list = request.POST.get('arg_list','') if request.POST.get('arg_list','') else []
			target = request.POST.get('target','').split(',')
			result = salt.run(fun=fun,target=target,arg_list=arg_list)
			job = {'user':user,'time':time.strftime("%Y-%m-%d %X", time.localtime()),'client':client,\
			'target':target,'fun':fun,'arg':arg_list,\
			'status':'','progress':'Finish','result':result,'cjid':str(int(round(time.time() * 1000)))}
			mongo_salt.salt_joblist.insert_one(job)
		except Exception as e:
			result = ''
			error = str(e)
	return render(request,'opsdb/salt/salt_run.html',locals())

@login_required
@role_required('salt','admin')
def salt_custom_run(request,arg_list):
	user = request.user.username
	if request.META.has_key('HTTP_X_FORWARDED_FOR'):
		client =  request.META['HTTP_X_FORWARDED_FOR']  
	else:
		client = request.META['REMOTE_ADDR']
	salt_master = get_object_or_404(ServiceHost,service='salt_api')
	salt = SaltAPI(salt_master.ip,salt_master.user,salt_master.password,port=salt_master.port)
	try:
		result = salt.run(fun='cmd.run',target=salt_master.hostname,arg_list=arg_list)
		job = {'user':user,'time':time.strftime("%Y-%m-%d %X", time.localtime()),'client':client,\
		'target':target,'fun':fun,'arg':arg_list,\
		'status':'','progress':'Finish','result':result,'cjid':str(int(round(time.time() * 1000)))}
		mongo_salt.salt_joblist.insert_one(job)
	except Exception as e:
		result = ''
		error = str(e)	
	return render(request,'opsdb/salt/salt_run.html',locals())

@login_required
@role_required('salt','admin')
def salt_state(request):
	states = SaltState.objects.all()
	if request.method == 'GET':
		pass
	else:
		user = request.user.username
		if request.META.has_key('HTTP_X_FORWARDED_FOR'):
			client =  request.META['HTTP_X_FORWARDED_FOR']  
		else:
			client = request.META['REMOTE_ADDR']
		salt_master = get_object_or_404(ServiceHost,service='salt_api')
		salt = SaltAPI(salt_master.ip,salt_master.user,salt_master.password,port=salt_master.port)
		try:
			arg_list = request.POST.get('arg_list','')
			target = request.POST.get('target','').split(',')
			result = {}
			err = []
			for tgt in target:
				metadata = ''.join(map(lambda xx:(hex(ord(xx))[2:]),os.urandom(16)))
				cmd = 'salt %s state.sls %s --metadata=%s'%(tgt,arg_list,metadata)
				jid = salt.run_async(fun='cmd.run',target=salt_master.hostname,arg_list=cmd)
				result[tgt] = jid['jid']
				job = {'user':user,'time':time.strftime("%Y-%m-%d %X", time.localtime()),'client':client,\
				'target':[tgt],'fun':'state.sls','arg':arg_list,'jid':jid['jid'],\
				'status':'','progress':'Executing','metadata':metadata}
				mongo_salt.salt_joblist.insert_one(job)
		except Exception as e:
			err.append(str(e))
	return render(request,'opsdb/salt/salt_state.html',locals())

@login_required
@role_required('salt','admin')
def saltjoblist(request):

ops/opsdb/templates/opsdb/salt/accept_key.html
{% extends 'opsdb/salt/minion_key.html' %}

{% block header %}
<header class="panel-heading tab-bg-dark-navy-blue ">
  <ul class="nav nav-tabs">
      <li class="">
          <a href="{%url 'opsdb:minion_key' 'pend' %}" style="left: 15px;">待签发</a>
      </li>
      <li class="active">
          <a onclick="window.location.reload()" style="left: 15px;">已签发</a>
      </li>
  </ul>
</header>
{% endblock %}


{% block button %}

{% endblock %}

ops/opsdb/templates/opsdb/salt/salt_job_result.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"  charset="utf-8">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

  </head>

  <body>

  	  <div class="col-lg-12">
  	{% if sjob.result %}
        {% for minion,return in sjob.result.items %}
<b>{{minion}}:</b>
        <pre>
{{return}}
        </pre>
        {% endfor %}
{% else %}
           <pre>
{{sjob.return}}
           </pre>
{% endif %}
  </div>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>

  </body>
</html>

ops/opsdb/templates/opsdb/salt/salt_jobs.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->

  </head>

  <body>

    <section class="wrapper site-min-height">
	{% block page %}
	    <!-- page start-->
	    <div class="row">
	      <div class="col-lg-12">
	          <!--breadcrumbs start -->
	          <ul class="breadcrumb">
	              <li><a href="#"></i>运维平台</a></li>
	              <li><a href="{% url 'opsdb:systems' %}"></i>主机管理</a></li>
	              <li class="active">操作记录</li>
	          </ul>
	          <!--breadcrumbs end -->
	      </div>
	    </div>
	    <section class="panel">
	     <!--  <header class="panel-heading tab-bg-dark-navy-blue ">
	          <ul class="nav nav-tabs">
	              <li class="active">
	                  <a onclick="window.location.reload()" style="left: 15px;">初始化</a>
	              </li>
	              <li class="">
	                  <a href="{%url 'installation:install'%}" style="left: 15px;">安装系统</a>
	              </li>
	          </ul>
	      </header> -->
	      {% block content %}
	      <div class="panel-body">
	          <div class="tab-content">
	              <div class="tab-pane active">
	                    <div class="mail-option">
	                           <div class="btn-group">
	                              <button type="button" class="btn label label-inverse" onclick="window.location.reload()"><i class="icon-refresh"></i> 刷新</button>
	                           </div>
	                          
	                           <div class="btn-group">
	                              <button type="button" class="btn label label-inverse" onclick="kill_job()"><i class="icon-stop"></i> Kill Job</button>
	                           </div>

	                           <div class="btn-group">
	                              <button type="button" class="btn label label-inverse" onclick="salt_run()"><i class="icon-search"></i> 搜索</button>
	                           </div>

	                           <ul class="unstyled inbox-pagination">
	                               <li>
	                                <span class="pages">合计:{{ paginator.count }}&nbsp</span>
	                                <span class="per-page">每页:</span>
	                                <select class="dropdown-select" name="page_number" onchange="javascript:window.location.href='?page_number='+ this.value;">
	                                   <option value="{{page_number}}">{{page_number}}</option>
	                                   <option value="10">10</option>
	                                   <option value="20">20</option>
	                                   <option value="50">50</option>
	                                   <option value="100">100</option>
	                                   <option value="10000">All</option>
	                                </select>
	                               </li>

	                               <li>
	                                 <span>&nbsp&nbsp{{ jobs.number }} / {{ jobs.paginator.num_pages }}</span>
	                               </li>
	                               
	                               <li>
	                                   {% if jobs.has_previous %}
	                                   <a href="?page={{ jobs.previous_page_number }}" class="np-btn"><i class="icon-angle-left  pagination-left"></i></a>
	                                   {% endif %}
	                               </li>
	                               <li>
	                                   {% if jobs.has_next %}
	                                   <a href="?page={{ jobs.next_page_number }}" class="np-btn"><i class="icon-angle-right pagination-right"></i></a>
	                                   {% endif %}
	                               </li>
	                           </ul>
	                    </div>
	                    <table class="table table-inbox table-hover" border="5" id='mytable'>
	                      <thead>
	                              <tr>
	                                <th><input type="checkbox" name="all" id="all"></th>
	                                <!-- <th><small>主机名</small></th> -->
	                                <th><small>用户</small></th>
	                                <th><small>时间</small></th>
	                                <th><small>客户端</small></th>
	                                <th><small>操作对象</small></th>
	                                <th><small>执行模块</small></th>
	                                <th><small>命令参数</small></th>
	                                <th><small>执行状态</small></th>
	                                <th><small>结果</small></th>
	                                <th><small>详细报告</small></th>
	                              </tr>
	                        </thead>
	                          <tbody>
	                            {% for job in jobs %}
	                              <tr>
	                                <td><input type="checkbox"></td>
	                                <!-- <td id="{{job.id}}">
	                                  <small><a onclick="show_system('{{job.id}}')" style="text-decoration:underline">{{job.id}}</a></small>
	                                </td> -->
	                                <td id="{{job.jid}}"><small>{{job.user}}</small></td>
	                                <td><small>{{job.time}}</small></td>
	                                <td><small>{{job.client}}</small></td>
	                                <td><small>{{job.target | join:','}}</small></td>
	                                <td><small>{{job.fun}}</small></td>
	                                <td><small>{{job.arg}}</small></td>
	                                {% if job.killed %}
	                                <th><small>{{job.killed}}</small></th>
	                                {% else %}
	                                <th><small>{{job.progress}}</small></th>
	                               	{% endif %}
	                                <th><small>{{job.status}}</small></th>
	                                {% if job.cjid %}
	                                <td><small><a onclick="show_job_result('job_cjid','{{job.cjid}}','{{job.target | join:','}}')">点击查看报告</a></small></td>
	                               	{% else %}
	                               	<td><small><a onclick="show_job_result('job_jid','{{job.jid}}','{{job.target | join:','}}')">点击查看报告</a></small></td>
	                               	{% endif %}
	                              </tr>
	                            {% endfor %}
	                          </tbody>
	                    </table>
	                  </div>
	          </div>
	      </div>
	      {% endblock %}
	    </section>
	    <!-- page end-->
	{% endblock %}
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/respond.min.js'%}" ></script>

    <!--common script for all pages-->
    <script src="{%static 'js/common-scripts.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>

    <script type="text/javascript">
        $(function() {
          var all_checked = false;
          $(":checkbox").click(function() {
              var table = $(this).parents("table");
              if($(this).attr("id") === "all") {
                  table.find(":checkbox").prop("checked", !all_checked);
                  all_checked = !all_checked;
              }
              else {
                  table.find(":checkbox[id!=all]").each(function (i) {
                      if(!$(this).is(":checked")) {
                          table.find("#all").prop("checked", false);
                          all_checked = false;
                          return false;
                      }
                      $("#all").prop("checked", true);
                      all_checked = true;
                  });
              }
          });
      });

    function show_job_result(url,job_id,target){
        var index = layer.open({
            type: 2,
            title: target,
            // offset: 'r',
            // maxmin: true,
            area: ['900px', '550px'],
            // area: 'auto',
            shadeClose: true,
            shift: 5,
            scrollbar: true,
            moveOut: true,
            content: '/opsdb/systems/' + url + '/' + job_id
          });
    }

      function get_server_id(){
        var tbodyObj = document.getElementById('mytable');
        var ids = [];
            $("table :checkbox").each(function(key,value){
                if($(value).prop('checked')){
                    if (value.id == 'all') return true
                    ids.push(tbodyObj.rows[key].cells[1].id);
                }
            });
            return ids
      }

      function kill_job(act) {
      	var ids = get_server_id();
      	// console.log(ids);
        if (ids.length == 0 )
        {
          layer.alert("请至少选中一台主机");
        }
        else if (ids.length > 1) 
        { layer.alert("该操作目前不支持批量操作");}
    	else
        {   
        	if (ids[0] == '')
        		{ layer.alert("该操作已完成,无法Kill");}
        	else
        	{
        		layer.confirm('请确认是否kill', function(index){
        		layer.load();
             	$.get("/opsdb/systems/kill_job/"+ids[0],function(data){
	                      layer.msg(data, function(){
									  window.location.reload();
									}); 
               		});       
            	}); 
        	}
            
        }
      }
    </script>
  </body>
</html>