ops/ops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$',views.base,name="base"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),    
	url(r'^accounts/login',views.login,name="login"),
	url(r'^logout/',views.logout,name="logout"),
    url(r'^users/',include('users.urls',namespace='users')),  
    url(r'^installation/',include('installation.urls',namespace='installation')),
    url(r'^opsdb/',include('opsdb.urls',namespace='opsdb')),
    url(r'^cronjob/',include('cronjob.urls',namespace='cronjob')),
]

ops/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^userlist/$',views.userlist,name='userlist'),
    url(r'^add_user/$',views.add_user,name='add_user'),
    url(r'^edit_user/(\d+)/$',views.edit_user,name='edit_user'),
    url(r'^disable_user/$',views.disable_user,name='disable_user'),
    url(r'^delete_user/$',views.delete_user,name='delete_user'),
    url(r'^reset_password/$',views.resetpwd,name='resetpwd'),
    url(r'^change_password/$',views.changepwd,name='changepwd'),
	url(r'^grouplist/$',views.grouplist,name='grouplist'),
    url(r'^add_group/$',views.add_group,name='add_group'),
    url(r'^edit_group/(\d+)/$',views.edit_group,name='edit_group'),
    url(r'^delete_group/$',views.delete_group,name='delete_group'),
    url(r'^profile/(\d+)/$',views.profile,name='profile'),
    url(r'^rulelist/$',views.rulelist,name='rulelist'),
    url(r'^edit_rule/(\d+)/$',views.edit_rule,name='edit_rule'),
]

ops/opsdb/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from installation.models import Environment
from django.contrib.auth.models import Group


# Create your models here.

class HostGroup(models.Model):
	id                 = models.AutoField(primary_key=True,db_column="group_id") 
	name               = models.CharField(max_length=50,blank=True,null=True)
	groups             = models.ManyToManyField(Group)
	comment            = models.TextField(max_length=200,blank=True)

	class Meta:
		db_table = 'hostgroup'

	def __unicode__(self):
		return self.name

class Business(models.Model):
	id                 = models.AutoField(primary_key=True,db_column="business_id") 
	name               = models.CharField(max_length=50,blank=True,null=True)
	environment        = models.ForeignKey(Environment,blank=True, null=True,on_delete=models.PROTECT)
	groups             = models.ManyToManyField(Group)
	comment            = models.TextField(max_length=200,blank=True)

	class Meta:
		db_table = 'business'

	def __unicode__(self):
		return self.name

class Application(models.Model):
	id                 = models.AutoField(primary_key=True,db_column="app_id") 
	name               = models.CharField(max_length=50,blank=True,null=True)
	business           = models.ForeignKey(Business,blank=True, null=True,on_delete=models.PROTECT)
	groups             = models.ManyToManyField(Group)
	comment            = models.TextField(max_length=200,blank=True)

	class Meta:
		db_table = 'application'

	def __unicode__(self):
		return self.name


class System(models.Model):
	id                 = models.CharField(primary_key=True,max_length=100,db_column="system_id")
	ip                 = models.GenericIPAddressField(blank=True,null=True)
	os                 = models.CharField(max_length=100,blank=True,null=True)
	num_cpus           = models.CharField(max_length=100,blank=True,null=True)
	mem_total          = models.CharField(max_length=100,blank=True,null=True)
	hostgroups         = models.ManyToManyField(HostGroup)
	applications       = models.ManyToManyField(Application)
	power_status       = models.BooleanField(default=True)
	minion_status      = models.BooleanField(default=True)
	is_delete          = models.BooleanField(default=False)
	comment            = models.TextField(max_length=200,blank=True)
	create_time        = models.DateTimeField(auto_now_add=True)
	update_time        = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = 'system'

	def __unicode__(self):
		return self.id

class ServiceHost(models.Model):
	ip                 = models.GenericIPAddressField(blank=True,null=True)
	hostname           = models.CharField(max_length=100,blank=True,null=True)
	port               = models.CharField(max_length=20,blank=True,null=True)
	user               = models.CharField(max_length=50,blank=True,null=True)
	password           = models.CharField(max_length=50,blank=True,null=True)
	service            = models.CharField(max_length=50,blank=True,null=True)

	class Meta:
		db_table = 'service_host'
	
	def __unicode__(self):
		return self.ip

class SaltFun(models.Model):
	id                 = models.AutoField(primary_key=True,db_column="salt_fun_id")
	name               = models.CharField(max_length=100,blank=True,null=True)

	class Meta:
		db_table = 'salt_fun'

	def __unicode__(self):
		return self.name


class SaltState(models.Model):
	id                 = models.AutoField(primary_key=True,db_column="salt_state_id")
	name               = models.CharField(max_length=100,blank=True,null=True)
	path               = models.CharField(max_length=100,blank=True,null=True)
	owner              = models.CharField(max_length=100,blank=True,null=True)
	comment            = models.TextField(max_length=200,blank=True)
	create_time        = models.DateTimeField(auto_now_add=True)
	update_time        = models.DateTimeField(auto_now=True)   


	class Meta:
		db_table = 'salt_state'

	def __unicode__(self):
		return self.name

ops/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

from django.contrib.auth.models import User,Group
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from opsdb.models import HostGroup,Application,Business

class Role(models.Model):
	name           = models.CharField(max_length=30, blank=True)
	comment        = models.TextField(max_length=100,blank=True)

	class Meta:
		db_table = 'role'

	def __str__(self):
		return self.name

class Profile(models.Model):
	user          = models.OneToOneField(User,related_name='profile', on_delete=models.CASCADE)
	roles         = models.ManyToManyField(Role)
	phone         = models.CharField(max_length=30, blank=True)
	wechat        = models.CharField(max_length=30, blank=True)
	date_expired  = models.DateTimeField(null=True)
	created_by    = models.ForeignKey(User,related_name='created_by',blank=True, null=True,on_delete=models.PROTECT)
	comment       = models.TextField(max_length=100,blank=True)

	class Meta:
		db_table = 'profile'

	def __str__(self):
		return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)
	instance.profile.save()

class Rule(models.Model):
	group         = models.OneToOneField(Group,related_name='rule', on_delete=models.CASCADE)
	hostgroups    = models.ManyToManyField(HostGroup)
	applications  = models.ManyToManyField(Application)
	businesses    = models.ManyToManyField(Business)
	created_by    = models.ForeignKey(User,blank=True, null=True,on_delete=models.PROTECT)
	comment       = models.TextField(max_length=100,blank=True)

	class Meta:
		db_table = 'rule'

	def __str__(self):
		return self.group.name

@receiver(post_save, sender=Group)
def create_or_update_group_rule(sender, instance, created, **kwargs):
	if created:
		Rule.objects.create(group=instance)
	instance.rule.save()		

ops/users/views.py
# encoding:utf-8
from django.shortcuts import render,redirect
from django.shortcuts import HttpResponse
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .custom_decorators import role_required
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User,Group
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
from .models import *
from opsdb.models import HostGroup,Application,Business
# Create your views here.

@login_required
@role_required('admin')
def userlist(request):
	user_list = User.objects.all()
	page_number =  request.GET.get('page_number')
	if page_number:
		page_number = int(page_number)
	else:
		page_number =  10
	paginator = Paginator(user_list, page_number)
	page = request.GET.get('page')
	try:
		users = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		users = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		users = paginator.page(paginator.num_pages)
	return render(request,'users/userlist.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def add_user(request):
	roles = Role.objects.all()
	groups = Group.objects.all()
	if request.method == "GET":
		return render(request, 'users/add_user.html',locals())
	else:
		try:
			username = request.POST.get('username','')
			# password = request.POST.get('password','')
			roles = request.POST.getlist('roles','')
			groups = request.POST.getlist('groups','')
			is_active = bool(int(request.POST.get('is_active','')))
			# date_expired = request.POST.get('date_expired','')
			email = request.POST.get('email','')
			phone = request.POST.get('phone','')
			wechat = request.POST.get('wechat','')
			comment = request.POST.get('comment','')
			user = User.objects.create(username=username,email=email,is_active=is_active)
			if user:
				user.set_password("1qaz@WSX")
				user.profile.roles = roles
				# user.profile.date_expired = date_expired
				user.profile.created_by = request.user
				if phone:
					user.profile.phone = phone
				if wechat:
					user.profile.wechat = wechat
				if comment:
					user.profile.comment = comment
				user.groups = groups
				user.save()
			result = {'status':True,'msg':'添加成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		return render(request, 'users/add_user.html',locals())

@login_required
@role_required('admin')
def edit_user(request,id):
	user = User.objects.get(id=id)
	roles = Role.objects.all()
	groups = Group.objects.all()
	if request.method == "GET":
		return render(request, 'users/edit_user.html',locals())
	else:
		try:
			username = request.POST.get('username','')
			new_roles = request.POST.getlist('roles','')
			new_groups = request.POST.getlist('groups','')
			# date_expired = request.POST.get('date_expired','')
			email = request.POST.get('email','')
			phone = request.POST.get('phone','')
			wechat = request.POST.get('wechat','')
			comment = request.POST.get('comment','')
			user.profile.roles = new_roles
			user.groups = new_groups
			# user.profile.date_expired = date_expired
			if username != user.username:
				user.username=username
			if email != user.email:
				user.email=email
			if phone != user.profile.phone:
				user.profile.phone = phone
			if wechat != user.profile.wechat:
				user.profile.wechat = wechat
			if comment != user.profile.comment:
				user.profile.comment = comment
			user.save()
			result = {'status':True,'msg':'更新成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		user = User.objects.get(id=id)
		return render(request, 'users/edit_user.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def delete_user(request):
	ids = request.POST.getlist('ids[]','')
	result = {}
	for user_id in ids:
		try:
			user = User.objects.get(pk=user_id)
			user.delete()
		except Exception as e:
			result[user.username] = '错误原因:%s'%(str(e))
	return HttpResponse(json.dumps(result))


@login_required
@role_required('admin')
@csrf_exempt
def disable_user(request):
	ids = request.POST.getlist('ids','')
	result = {}
	for user_id in ids:
		try:
			user = User.objects.get(pk=user_id)
			user.is_active = not user.is_active
			user.save()
		except Exception as e:
			result[user.username] = '错误原因:%s'%(str(e))
	return HttpResponse(json.dumps(result))


@login_required
def profile(request,id):
	user = User.objects.get(id=id)
	if request.method == "GET":
		return render(request, 'users/profile.html',locals())
	else:
		try:
			username = request.POST.get('username','')
			email = request.POST.get('email','')
			phone = request.POST.get('phone','')
			wechat = request.POST.get('wechat','')
			comment = request.POST.get('comment','')
			if username != user.username:
				user.username=username
			if email != user.email:
				user.email=email
			if phone != user.profile.phone:
				user.profile.phone = phone
			if wechat != user.profile.wechat:
				user.profile.wechat = wechat
			if comment != user.profile.comment:
				user.profile.comment = comment
			user.save()
			result = {'status':True,'msg':'更新成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		user = User.objects.get(id=id)
		return render(request, 'users/profile.html',locals())


@login_required
def changepwd(request):
	if request.method == 'GET':
		return render(request, 'users/changepwd.html')
	else:
		oldpassword = request.POST.get('oldpassword', '')
		user = auth.authenticate(username=request.user.username, password=oldpassword)
		if user:
			newpassword = request.POST.get('newpassword', '')
			newpassword1 = request.POST.get('newpassword1', '')
			if newpassword == newpassword1:
				user.set_password(newpassword)
				user.save()
				result = {'status':True,'msg':'密码修改成功'}
			else:
				result = {'status':False,'msg':'两次输入密码不同'}
		else:
			result = {'status':False,'msg':'旧密码错误！'}
		return render(request, 'users/changepwd.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def resetpwd(request):
	ids = request.POST.getlist('ids','')
	result = {}
	for user_id in ids:
		try:
			user = User.objects.get(pk=user_id)
			user.set_password('1qaz@WSX')
			user.save()
		except Exception as e:
			result[user.username] = '重置密码失败,原因:%s'%(str(e))
	return HttpResponse(json.dumps(result))

@login_required
@role_required('admin')
def grouplist(request):
	group_list = Group.objects.all()
	page_number =  request.GET.get('page_number')
	if page_number:
		page_number = int(page_number)
	else:
		page_number =  10
	paginator = Paginator(group_list, page_number)
	page = request.GET.get('page')
	try:
		groups = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		groups = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		groups = paginator.page(paginator.num_pages)
	return render(request, 'users/grouplist.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def add_group(request):
	users = User.objects.all()
	if request.method == "GET":
		return render(request, 'users/add_group.html',locals())
	else:
		name = request.POST.get('name','')
		members = request.POST.getlist('members','')
		try:
			group = Group.objects.create(name=name)
			if group and members:
				group.user_set = members
			result = {'status':True,'msg':'添加成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		return render(request, 'users/add_group.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def edit_group(request,id):
	group = Group.objects.get(id=id)
	users = User.objects.all()
	if request.method == "GET":
		return render(request,'users/edit_group.html',locals())
	else:
		name = request.POST.get('name','')
		members = request.POST.getlist('members','')
		try:
			if group.name != name:
				group.update(name=name)
			group.user_set = members
			result = {'status':True,'msg':'更新成功'}
		except Exception as e:
			result = {'status':False,'msg':str(e)}
		return render(request, 'users/edit_group.html',locals())

@login_required
@role_required('admin')
@csrf_exempt
def delete_group(request):
	ids = request.POST.getlist('ids[]','')
	result = {}
	for group_id in ids:
		try:
			group = Group.objects.get(pk=group_id)
			group.delete()
		except Exception as e:
			result[group.name] = str(e)
	return HttpResponse(json.dumps(result))

@login_required
@role_required('admin')
def rulelist(request):
	rule_list = Rule.objects.all()
	page_number =  request.GET.get('page_number')
	if page_number:
		page_number = int(page_number)
	else:
		page_number =  10
	paginator = Paginator(rule_list, page_number)
	page = request.GET.get('page')
	try:
		rules = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		rules = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		rules = paginator.page(paginator.num_pages)	
	return render(request,'users/rulelist.html',locals())


@login_required
@role_required('admin')
@csrf_exempt
def edit_rule(request,id):
	hostgroups = HostGroup.objects.all()
	apps = Application.objects.all()
	businesses = Business.objects.all()
	rule = Rule.objects.get(pk=id)
	if request.method == "GET":
		return render(request, 'users/edit_rule.html',locals())
	else:
		try:
			hostgroups = request.POST.getlist('hostgroups','')
			apps = request.POST.getlist('apps','')
			businesses = request.POST.getlist('businesses','')
			comment = request.POST.get('comment','')
			rule.hostgroups = hostgroups
			rule.applications = apps
			rule.businesses = businesses
			rule.created_by = request.user
			rule.comment = comment
			rule.save()
			result = {'status':True,'msg':'添加成功'}
		except Exception as e:

ops/users/templates/users/rulelist.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->


  </head>

  <body>

    <section class="wrapper site-min-height">
        <!-- page start-->
        <div class="row">
          <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb">
                  <li><a href="#"></i>安全及权限</a></li>
                  <li class="active">授权规则</li>
              </ul>
              <!--breadcrumbs end -->
          </div>
        </div>
        <section class="panel">
       <!--    <header class="panel-heading tab-bg-dark-navy-blue ">
              <ul class="nav nav-tabs">
                  <li class="active">
                      <a onclick="window.location.reload()" style="left: 15px;">用户</a>
                  </li>
                  <li class="">
                      <a href="{% url 'users:grouplist'%}" style="left: 15px;">用户组</a>
                  </li>
              </ul>
          </header> -->
          <div class="panel-body">
              <div class="tab-content">
                  <div class="tab-pane active">
                        <div class="mail-option">
                               <div class="btn-group">
                                  <button type="button" class="btn label label-inverse" onclick="window.location.reload()"><i class="icon-refresh"></i> 刷新</button>
                               </div>
                               <div class="btn-group">
                                   <button type="button" class="btn label label-inverse" onclick="edit_rule()"><i class="icon-plus"></i> 编辑规则</button>
                               </div>
                               <div class="btn-group">
                                   <button type="button" class="btn label label-inverse" onclick="delete_rule()"><i class="icon-trash"></i> 删除规则</button>
                               </div>
                              <!--  <div class="btn-group hidden-phone">
                                      <button data-toggle="dropdown" class="btn label label-inverse dropdown-toggle" type="button"><i class="icon-th-large"></i>&nbsp更多操作&nbsp&nbsp <span class="caret"></span></button>
                                      <ul role="menu" class="dropdown-menu" style="min-width: 101.63px;width: 101.63px;">
                                          <li><a onclick="reset_pwd()" style="padding-left: 5px;"><small>重置密码</small></a></li>
                                          <li><a onclick="disable_user()" style="padding-left: 5px;"><small>禁用/启用账户</small></a></li>
                                      </ul>
                                 </div> -->

                               <ul class="unstyled inbox-pagination">
                                   <li>
                                    <span class="pages">合计:{{ paginator.count }}&nbsp</span>
                                    <span class="per-page">每页:</span>
                                    <select class="dropdown-select" name="page_number" onchange="javascript:window.location.href='?page_number='+ this.value;">
                                       <option value="{{page_number}}">{{page_number}}</option>
                                       <option value="10">10</option>
                                       <option value="20">20</option>
                                       <option value="50">50</option>
                                       <option value="100">100</option>
                                    </select>
                                   </li>

                                   <li>
                                     <span>&nbsp&nbsp{{ rules.number }} / {{ rules.paginator.num_pages }}</span>
                                   </li>
                                   
                                   <li>
                                       {% if rules.has_previous %}
                                       <a href="?page={{ rules.previous_page_number }}" class="np-btn"><i class="icon-angle-left  pagination-left"></i></a>
                                       {% endif %}
                                   </li>
                                   <li>
                                       {% if rules.has_next %}
                                       <a href="?page={{ rules.next_page_number }}" class="np-btn"><i class="icon-angle-right pagination-right"></i></a>
                                       {% endif %}
                                   </li>
                               </ul>
                        </div>
                        <table class="table table-inbox table-hover" border="5" id='mytable'>
                          <thead>
                                  <tr>
                                    <th><input type="checkbox" name="all" id="all"></th>
                                    <th><small>用户组</small></th>
                                    <th><small>用户数</small></th>
                                    <th><small>主机组(包含主机数)</small></th>
                                    <th><small>应用</small></th>
                                    <th><small>业务</small></th>
                                    <th><small>创建者</small></th>
                                    <th><small>备注</small></th>
                                    <!-- <th><small>操作</small></th> -->
                                    
                                  </tr>
                            </thead>
                              <tbody>
                                {% for rule in rules %}
                                  <tr>
                                    <td><input type="checkbox"></td>
                                    <td id="{{rule.id}}"><small>{{rule.group.name}}</small></td>
                                    <td><small>{{rule.group.user_set.count}}</small></td>
                                    <td>
                                      <small>
                                        {% for hostgroup in rule.hostgroups.all %}
                                          <li>{{hostgroup.name}}({{hostgroup.system_set.count}})</li>
                                        {% endfor %}
                                      </small>
                                    </td>
                                    <td>
                                      <small>
                                        {% for app in rule.applications.all %}
                                          <li>{{app.name}}</li>
                                        {% endfor %}
                                      </small>
                                    </td>
                                    <td>
                                      <small>
                                        {% for business in rule.businesses.all %}
                                          <li>{{business.name}}</li>
                                        {% endfor %}
                                      </small>
                                    </td>
                                    <td><small>{{rule.created_by.username}}</small></td>
                                    <td><small>{{rule.comment}}</small></td>
                                   <!--  <td><small><button data-placement="left" data-toggle="tooltip" class="label label-inverse tooltips" data-original-title="编辑授权规则" onclick="edit_rule('{{user.id}}')" style="padding-left: 5px;">编辑规则</button></small></td> -->
                                  </tr>
                                {% endfor %}
                              </tbody>
                        </table>
                      </div>
              </div>
          </div>
        </section>
        <!-- page end-->
    </section>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script class="include" type="text/javascript" src="{%static 'js/jquery.dcjqaccordion.2.7.js'%}"></script>
    <script src="{%static 'js/jquery.scrollTo.min.js'%}"></script>
    <script src="{%static 'js/jquery.nicescroll.js'%}" type="text/javascript"></script>
    <script src="{%static 'js/respond.min.js'%}" ></script>

    <!--common script for all pages-->
    <script src="{%static 'js/common-scripts.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>

    <script type="text/javascript">
        $(function() {
          var all_checked = false;
          $(":checkbox").click(function() {
              var table = $(this).parents("table");
              if($(this).attr("id") === "all") {
                  table.find(":checkbox").prop("checked", !all_checked);
                  all_checked = !all_checked;
              }
              else {
                  table.find(":checkbox[id!=all]").each(function (i) {
                      if(!$(this).is(":checked")) {
                          table.find("#all").prop("checked", false);
                          all_checked = false;
                          return false;
                      }
                      // $("#all").prop("checked", true);
                      all_checked = true;
                  });
              }
          });
      });

      function get_server_id(){
        var tbodyObj = document.getElementById('mytable');
        var ids = [];
            $("table :checkbox").each(function(key,value){
                if($(value).prop('checked')){
                    // alert(tbodyObj.rows[key].cells[1].innerHTML);
                    ids.push(tbodyObj.rows[key].cells[1].id);
                }
            });
            return ids
      }


      function edit_rule() {
        var ids = get_server_id();
        if (ids.length ==0 )
        {
          layer.alert("请先选中一条授权规则");
        }
        else if (ids.length > 1)
        {
          layer.alert("该操作不支持批量操作");
        }
        else
        {   
          var index = layer.open({
            type: 2,
            title: "添加授权规则",
            area: ['700px', '520px'],
            shadeClose: true,
            shift: 5,
            moveOut: true,
            content: "/users/edit_rule/"+ids[0],
            end: function () {
                  window.location.reload();//刷新
                }
          });
        }
      }

      function delete_user() {
        var ids = get_server_id();
        if (ids.length ==0 )
        {
          layer.alert("请至少选中一个账户");
        }
        else
        {   

            layer.confirm('请确认是否要删除账户', function(index){
                  $.post("{% url 'users:delete_user' %}",{'ids':ids.toString()},function(data){
                    if (data == '{}')
                    {
                      layer.msg('删除成功',function(){
                        window.location.reload();
                      });
                    }
                    else
                    {
                      layer.alert('删除失败:' + data, function(){
                              window.location.reload();
                            });
                    }
                  });
                      
            }); 
        }
      }
    </script>
  </body>
</html>