ops/installation/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.views.decorators.csrf import csrf_exempt
from . import views

urlpatterns = [
    url(r'^post_server_info/',views.post_server_info,name='post_server_info'),
    url(r'^servers/$',views.server,name='server'),
    url(r'^servers/init/',views.init,name='init'),
    url(r'^servers/install/',views.install,name='install'),
    url(r'^server/detail/(\w+)/$',views.server_detail,name='server_detail'),
    url(r'^server/delete/',views.server_delete,name='server_delete'),
    url(r'^server/edit/(\w+)/$',views.server_edit,name='server_edit'),
    url(r'^server/raid/(\w+)/(\w+)/(\w*)',views.server_raid,name='server_raid'),
    url(r'^select_cab/',views.select_cab,name='select_cab'),
    url(r'^server/status/',views.server_change_status,name='server_change_status'),
    url(r'^server/ipmi/(\w+)/(\w+)/$',views.server_ipmi,name='server_ipmi'),
    url(r'^server/ipmi/(\w+)/$',views.update_ipmi,name='update_ipmi'),
    url(r'^install_pre_post/$',views.install_pre_post,name='install_pre_post'),
    url(r'^server/install/(\w+)/$',views.get_system,name='get_system'),
    url(r'^server/add_system/(\w+)/$',views.add_system,name='add_system'),
    url(r'^server/edit_system/(\w+)/(\w+)/$',views.edit_system,name='edit_system'),
    url(r'^server/system/view/(\w+)/$',views.view_system,name='view_system'),
    url(r'^server/system/delete/(\w+)/(\w+)/$',views.delete_system,name='delete_system'),
    url(r'^celery/$',views.tasks,name='tasks'),
    url(r'^vm/vcenter/$',views.vcenter,name='vcenter'),
    url(r'^vm/add_vcenter/$',views.add_vcenter,name='add_vcenter'),
    url(r'^vm/edit_vcenter/(\d+)/$',views.edit_vcenter,name='edit_vcenter'),
    url(r'^vm/delete_vcenter/(\d+)/$',views.delete_vcenter,name='delete_vcenter'),
    url(r'^vm/add_vm/$',views.add_vm,name='add_vm'),
    url(r'^vm/get_obj',views.get_obj,name='get_obj'),
    url(r'^installserver/$',views.cobbler,name='cobbler'),
    url(r'^installserver/add/$',views.add_cobbler,name='add_cobbler'),
    url(r'^installserver/edit/(\d+)/$',views.edit_cobbler,name='edit_cobbler'),
]

ops/ops/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
	url(r'^admin/', admin.site.urls),
	url(r'^$',views.base,name="base"),
    url(r'^dashboard/$',views.dashboard,name="dashboard"),    
	url(r'^accounts/login',views.login,name="login"),
	url(r'^logout/',views.logout,name="logout"),
    url(r'^users/',include('users.urls',namespace='users')),  
    url(r'^installation/',include('installation.urls',namespace='installation')),
    url(r'^opsdb/',include('opsdb.urls',namespace='opsdb')),
    url(r'^cronjob/',include('cronjob.urls',namespace='cronjob')),
]

ops/installation/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class Idc(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="idc_id")
    name               = models.CharField(max_length=100,blank=True,null=True,db_column="idc_name")
    class Meta:
        db_table = 'idc'

    def __unicode__(self):
        return self.name

class Cabinet(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="cabinet_id")    
    name               = models.CharField(max_length=100,blank=True,null=True,db_column="cabinet_name")
    size               = models.IntegerField(blank=True,null=True,db_column="cabinet_size")
    idc                = models.ForeignKey(Idc,blank=True, null=True,on_delete=models.PROTECT)
    class Meta:
        db_table = 'cabinet'

    def __unicode__(self):
        return self.name

class Environment(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="environment_id")
    name               = models.CharField(max_length=100,blank=True,null=True,db_column="environment_name")
    comment            = models.TextField(max_length=200,blank=True)
    class Meta:
        db_table = 'environment'

    def __unicode__(self):
        return self.name

class ServerStatus(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="server_status_id")
    status_type        = models.CharField(max_length=50,blank=True,null=True,db_column="server_status_type")
    name               = models.CharField(max_length=100,blank=True,null=True,db_column="server_status_name")
    class Meta:
        db_table = 'server_status'

    def __unicode__(self):
        return self.status_type

class Contacter(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="contacter_id")
    name               = models.CharField(max_length=30,blank=True,null=True)
    phone              = models.CharField(max_length=30,blank=True,null=True)
    email              = models.EmailField(blank=True,null=True)
    dept               = models.CharField(max_length=30,blank=True,null=True)
    company            = models.CharField(max_length=30,blank=True,null=True)

    class Meta:
        db_table = 'contacter'

    def __unicode__(self):
        return self.name

class Tag(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="tag_id")
    tag_type           = models.CharField(max_length=10,blank=True,null=True)
    description        = models.CharField(max_length=30,blank=True,null=True)

    class Meta:
        db_table = 'tag'

    def __unicode__(self):
        return self.tag_type           

class Server(models.Model):
    id                 = models.CharField(max_length=100,primary_key=True,db_column="server_id")
    sn                 = models.CharField(max_length=100,blank=True,null=True)
    cpu_model          = models.CharField(max_length=100,blank=True,null=True)
    cpu_sockets        = models.IntegerField(blank=True,null=True)
    cpu_cores          = models.IntegerField(blank=True,null=True)
    cpu_threads        = models.IntegerField(blank=True,null=True)
    mem_size           = models.IntegerField(blank=True,null=True)
    mem_total_slots    = models.IntegerField(blank=True,null=True)
    mem_free_slots     = models.IntegerField(blank=True,null=True)
    raid_adapter       = models.CharField(max_length=200,blank=True,null=True)
    raid_adapter_slot  = models.CharField(max_length=20,blank=True,null=True)
    cabinet            = models.ForeignKey(Cabinet,blank=True, null=True,on_delete=models.PROTECT)
    environment        = models.ForeignKey(Environment,blank=True, null=True,on_delete=models.PROTECT)
    serverstatus       = models.ForeignKey(ServerStatus,blank=True, null=True,on_delete=models.PROTECT)
    ipmi_ip            = models.GenericIPAddressField(blank=True,null=True)
    ipmi_user          = models.CharField(max_length=30,blank=True,null=True)
    ipmi_pass          = models.CharField(max_length=30,blank=True,null=True)
    tag                = models.ForeignKey(Tag,blank=True, null=True,on_delete=models.PROTECT)
    unit               = models.IntegerField(blank=True,null=True)
    contacter          = models.ForeignKey(Contacter,blank=True, null=True,on_delete=models.PROTECT)
    pxe_mac            = models.CharField(max_length=30,blank=True,null=True)
    pxe_ip             = models.GenericIPAddressField(blank=True,null=True)
    vendor             = models.CharField(max_length=30,blank=True,null=True)
    model              = models.CharField(max_length=30,blank=True,null=True)
    prod_ip            = models.GenericIPAddressField(blank=True,null=True)
    power              = models.CharField(max_length=10,blank=True,null=True,default='on')
    create_time        = models.DateTimeField(auto_now_add=True)
    update_time        = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'server'
        ordering = ['-create_time']

    def __unicode__(self):
        return self.id

class Disk(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="disk_id")
    path               = models.CharField(max_length=30,blank=True,null=True,db_column="disk_name")
    dtype              = models.CharField(max_length=30,blank=True,null=True,db_column="disk_model")
    server             = models.ForeignKey(Server,blank=True, null=True)
    raid_name          = models.CharField(max_length=100,blank=True,null=True)
    raid_type          = models.CharField(max_length=100,blank=True,null=True)
    size               = models.CharField(max_length=30,blank=True,null=True,db_column="disk_size")

    class Meta:
        db_table = 'disk'

    def __unicode__(self):
        return self.path

class Nic(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="nic_id")
    name               = models.CharField(max_length=20,blank=True,null=True,db_column="nic_name")
    mac                = models.CharField(max_length=50,blank=True,null=True,db_column="mac")
    model              = models.CharField(max_length=100,blank=True,null=True,db_column="nic_model")
    server             = models.ForeignKey(Server,blank=True, null=True)

    class Meta:
        db_table = 'nic'
    
    def __unicode__(self):
        return self.mac

class PreSystem(models.Model):
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)
    hostname           = models.CharField(max_length=50,blank=True,null=True)
    profile            = models.CharField(max_length=50,blank=True,null=True)
    progress           = models.IntegerField(blank=True,null=True,default=-1)
    server             = models.OneToOneField(Server,blank=True, null=True)
    create_time        = models.DateTimeField(auto_now_add=True)
    update_time        = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'pre_system'
        ordering = ['-create_time']
    
    def __unicode__(self):
        return self.profile

class Vcenter(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="vc_id")
    name               = models.CharField(max_length=50,blank=True,null=True,db_column="vc_name")
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)
    port               = models.CharField(max_length=10,default='443')
    user               = models.CharField(max_length=50,blank=True,null=True)
    password           = models.CharField(max_length=50,blank=True,null=True)

    class Meta:
        db_table = 'vcenter'
    
    def __unicode__(self):
        return self.name

class Datastore(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="datastore_id")
    name               = models.CharField(max_length=50,blank=True,null=True,db_column="datastore_name")
    capacity           = models.CharField(max_length=50,blank=True,null=True)
    free_space         = models.CharField(max_length=50,blank=True,null=True)
    provisioned        = models.CharField(max_length=50,blank=True,null=True)
    uncommitted        = models.CharField(max_length=50,blank=True,null=True)
    hosts              = models.IntegerField(blank=True,null=True,default=0)
    vms                = models.IntegerField(blank=True,null=True,default=0)
    vcenter            = models.ForeignKey(Vcenter,blank=True, null=True,on_delete=models.PROTECT)

    class Meta:
        db_table = 'vm_datastore'
    
    def __unicode__(self):
        return self.name

class Datacenter(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="dc_id")
    name               = models.CharField(max_length=50,blank=True,null=True,db_column="dc_name")
    vcenter            = models.ForeignKey(Vcenter,blank=True, null=True,on_delete=models.PROTECT)

    class Meta:
        db_table = 'vm_datacenter'
    
    def __unicode__(self):
        return self.name
          
class Cluster(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="ha_id")
    name               = models.CharField(max_length=50,blank=True,null=True,db_column="ha_name")
    datacenter         = models.ForeignKey(Datacenter,blank=True, null=True,on_delete=models.PROTECT)

    class Meta:
        db_table = 'vm_cluster'
    
    def __unicode__(self):
        return self.name

class Host(models.Model):
    id                 = models.AutoField(primary_key=True,db_column="host_id")
    ip                 = models.GenericIPAddressField(blank=True,null=True,unique=True)    
    cluster            = models.ForeignKey(Cluster,blank=True, null=True,on_delete=models.PROTECT)
    server             = models.OneToOneField(Server,blank=True, null=True, on_delete=models.PROTECT)

    class Meta:
        db_table = 'vm_host'
    
    def __unicode__(self):
        return self.ip

ops/installation/templates/installation/add_vcenter.html
{% extends "installation/add_system.html" %}

{% block content %}
      {% if messages %}
              {% for message in messages %}
                  {% if message.tags == 'error' %}
                      <p class="alert alert-block alert-danger fade in">{{ message }}</p>
                  {% else %}
                      <p class="alert alert-success fade in">{{ message }}</p>
                  {% endif %}
              {% endfor %}
      {% endif %} 
    <form class="form-horizontal" role="form" action="{% url 'installation:add_vcenter' %}" method="post" role="form">
        {% csrf_token %}
          <div class="form-group">
            <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">Vcenter Name *</span></label>
            <div class="col-xs-8 col-md-6 col-sm-6" >
                  <input class="form-control" name="name" required="required" type="text">
            </div>
          </div>

      
          <div class="form-group">
            <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span>IP *</span></label>
            <div class="col-xs-8 col-md-6 col-sm-6">
                <input class="form-control" name="ip" required="required" type="text">
            </div>
          </div>


          <div class="form-group" >
            <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">Port *</span></label>
            <div class="col-xs-8 col-md-6 col-sm-6" >
              <input class="form-control" name="port" required="required" type="text" value="443">
            </div>
          </div>

          <div class="form-group" >
            <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">User *</span></label>
            <div class="col-xs-8 col-md-6 col-sm-6" >
              <input class="form-control" name="user" required="required" type="text">
            </div>
          </div>

          <div class="form-group" >
            <label class="col-md-3 col-sm-3 col-xs-3 control-label"><span class="required">Password *</span></label>
            <div class="col-xs-8 col-md-6 col-sm-6" >
              <input class="form-control" name="password" required="required" type="password">
            </div>
          </div>

          <div class="form-group">
            <div class="col-xs-8 col-md-6 col-sm-6">
              <button type="submit" class="btn">Submit</button>
            </div>
          </div>
        </form>
{% endblock %}

ops/installation/templates/installation/add_vm.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="{%static 'img/favicon.ico'%}">

    {% block title %}
    <title> 自动化运维平台 </title>
    {% endblock %}

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{%static 'css/bootstrap-reset.css'%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static 'assets/font-awesome/css/font-awesome.css'%}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{%static 'css/style.css'%}" rel="stylesheet">
    <link href="{%static 'css/style-responsive.css'%}" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{%static 'js/html5shiv.js'%}"></script>
      <script src="{%static 'js/respond.min.js'%}"></script>
    <![endif]-->
  </head>

  <body>
    <section class="wrapper site-min-height">
        <!-- page start-->
        <div class="row">
          <div class="col-lg-12">
              <!--breadcrumbs start -->
              <ul class="breadcrumb">
                  <li><a href="#"></i>部署平台</a></li>
                  <li><a href="#">虚拟机安装</a></li>
                  <li class="active">新建虚拟机</li>
              </ul>
              <!--breadcrumbs end -->
          </div>
        </div>
        <section class="panel">
          <div class="panel-body">
              <form class="form-horizontal" role="form" action="{% url 'installation:add_vm' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>VM_Name *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                          <input class="form-control" name="vm_name" required="required" type="text">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>VM_CPU *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                          <input class="form-control" name="vm_cpus" required="required" type="text">
                      </div>
                    </div>
                   
                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>VM_CPU_Socket *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                          <input class="form-control" name="vm_cpu_sockets" required="required" type="text">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>VM_Memery(M) *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                          <input class="form-control" name="vm_memory" required="required" type="text">
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>Power *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <select name="power" required="required">
                          <option value ="1">On</option>
                          <option value ="0">Off</option>
                        </select>
                      </div>
                    </div>
                  
                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>Template *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <select name="template" required="required">
                          <option value ="-1">--请选择--</option>
                          {% for template in templates %}
                            <option value ="{{template.name}}">{{template.name}}</option>
                          {% endfor %}
                        </select>
                      </div>
                    </div>
              
                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>Vcenter *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <select name="vcenter" id='vc' onchange="get_obj('vc','dc')" required="required">
                          <option value ="-1">--请选择--</option>
                          {% for vcenter in vcenters %}
                            <option value ="{{vcenter.name}}">{{vcenter.name}}</option>
                          {% endfor %}
                        </select>
                      </div>
                    </div>


                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>DataCenter *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <select name="datacenter" id='dc' onchange="get_obj('dc','cluster')" required="required">
                          <option value ="-1">--请选择--</option>
                        </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>Cluster *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <select name="cluster" id='cluster' onchange="get_obj('cluster','esxi')" required="required">
                          <option value ="-1">--请选择--</option>
                        </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <label class="col-lg-2 col-md-3 col-sm-3 col-xs-3 control-label" style="width: 150px;"><span>DataStore *</span></label>
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <select name="datastore" id='ds' required="required">
                          <option value ="-1">--请选择--</option>
                        </select>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-xs-8 col-md-6 col-sm-6">
                        <button type="submit" class="btn">Submit</button>
                      </div>
                    </div>
              </form>
          </div>          
        </section>
        <!-- page end-->
    </section>

  <script type="text/javascript">
    function get_obj(this_id,next_id){
      var val=$("#"+this_id).val();
      $("#"+next_id).empty();
      if(val!="-1"){
        $.ajax({
          type:"GET",
          url:'/installation/vm/get_obj',
          data:{'type':this_id,'val':val},
          dataType:"Json",
          async : false, 
          success:function(result){
             $("#"+next_id).append("<option value = '" + '-1'  + "'>" + '--请选择--' + "</option>");
             $.each(result,function(key,value)
                {
                  $("#"+next_id).append("<option value = '" + key  + "'>" + value + "</option>");
                }
             );
             if (this_id == 'vc'){
                $("#ds").empty();
                $.ajax({
                    type:"GET",
                    url:'/installation/vm/get_obj',
                    data:{'type':'ds','val':val},
                    dataType:"Json",
                    async : false, 
                    success:function(result){
                       $("#ds").append("<option value = '" + '-1'  + "'>" + '--请选择--' + "</option>");
                       $.each(result,function(key,value)
                          {
                            $("#ds").append("<option value = '" + key  + "'>" + value + "</option>");
                          }
                       );
                    }
                });
             }
          }
        });
      };
    }
  </script>
  </body>
</html>

ops/installation/templates/installation/msg.html
{% load staticfiles %}
<script src="{%static 'layer/layer.js'%}"></script>

<script type="text/javascript">
	// layer.alert('{{ret_data}}',function() {
	// 	location.reload();
	// });
	layer.msg('{{ret_data}}');
	// $(document).ready(function(){
	// 	  layer.msg('{{ret_data}}');
	// 	});
</script>

ops/installation/templates/installation/server.html
{% extends 'iframe.html' %}
{% load staticfiles %}

{% block title %}   
<title> 装机管理 | 自动化运维平台 </title>
{% endblock %}


{% block content %}
<iframe src="{% url 'installation:init'%}" id="myiframe" scrolling="no" onload="changeFrameHeight()" frameborder="0" width="100%"></iframe>
{% endblock %}


{% block js %}
<script type="text/javascript">
  function changeFrameHeight(){
    var ifm= document.getElementById("myiframe"); 
    ifm.height=document.documentElement.clientHeight;
  }

  window.onresize=function(){  
     changeFrameHeight();  
  } 
</script>
{% endblock %}

ops/installation/templates/installation/server_detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1"  charset="utf-8">

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

  </head>

  <body>
        <a href="#" class="list-group-item active" style="background-color: #444f58;">
            <h4 class="list-group-item-heading">
                基本信息
            </h4>
        </a>

        <div class="col-xs-12 col-sm-12">
            <br>
            <ul class="list-group">
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">服务器 ID:</b>{{server.id}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">服务器厂商:</b> {{server.vendor}}</li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">服务器型号:</b> {{server.model}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">PXE IP:</b> {{server.pxe_ip}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">IPMI IP:</b> {{server.ipmi_ip}}</li>
            </ul>
        </div>

        <a href="#" class="list-group-item active" style="background-color: #444f58;">
            <h4 class="list-group-item-heading">
                硬件信息
            </h4>
        </a>

        <br/>
        <div class="col-xs-12 col-sm-12">
            <br>
            <p class="list-group-item-text">
                <h5 class="list-group-item-heading">CPU信息:</h5>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU型号:</b>{{server.cpu_model}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU Sockets:</b> {{server.cpu_sockets}}</li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU Cores:</b> {{server.cpu_cores}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">CPU Threads:</b> {{server.cpu_threads}}</li>
            </p>
        </div>

        <div class="col-xs-12 col-sm-12">
            <br>
            <p class="list-group-item-text">
                <h5 class="list-group-item-heading">内存信息:</h5>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">总内存(G):</b>{{server.mem_size}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">槽位数:</b> {{server.mem_total_slots}}</li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">剩余槽位:</b> {{server.mem_free_slots}}</li>
            </p>          
        </div>



       <div class="col-xs-12 col-sm-12">
          <br>
          <h5 class="list-group-item-heading">硬盘信息:</h5>
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <td>硬盘路径</td>
                    <td>大小</td>
                    <td>类型</td>
                  </tr>
                </thead>
                
                <tbody>
                {% for disk in server.disk_set.all %}
                  <tr>
                    <td>{{disk.path}}</td>
                    <td>{{disk.size}}</td>
                    <td>{{disk.dtype}}</td>
                  </tr>
                {% endfor %}
                </tbody>
            </table>        
       </div>
 
        <!-- </p> -->
 
      <div class="col-xs-12 col-sm-12">
        <br>
        <h5 class="list-group-item-heading">网卡信息:</h5>
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <td>名称</td>
                    <td>MAC</td>
                    <td>型号</td>
                  </tr>
                </thead>
                
                <tbody>
                {% for nic in server.nic_set.all %}
                  <tr>
                    <td>{{nic.name}}</td>
                    <td>{{nic.mac}}</td>
                    <td>{{nic.model}}</td>
                {% endfor %}
                </tbody>
            </table>
       </div>

        <a href="#" class="list-group-item active" style="background-color: #444f58;">
            <h4 class="list-group-item-heading">
                附加信息
                <button onclick="edit_server('{{server.id}}')" class="btn btn-xs">编辑</button>
            </h4>
        </a>

       <div class="col-xs-12 col-sm-12">
            <br>
            <ul class="list-group">
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">机房:</b>
                {% if server.cabinet.idc.name %}
                  {{server.cabinet.idc.name}}
                {% else %}
                  None
                {% endif %}  
                </li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">机柜:</b>
                {% if server.cabinet.name %}
                  {{server.cabinet.name}}
                {% else %}
                  None
                {% endif %} 
                </li> 
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">位置(U):</b> {{server.unit}}</li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">环境:</b>
                {% if server.environment %}
                  {{server.environment.name }}
                {% else %}
                  None
                {% endif %}         
                </li>
                <li class="list-group-item"><b class="col-xs-3 col-sm-3 text-right">联系人:</b>
                {% if server.contacter %}
                  {{server.contacter.name }}
                {% else %}
                  None
                {% endif %}         
                </li>
            </ul>
        </div>

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script src="{%static 'layer/layer.js'%}"></script>
    <script type="text/javascript">
            function edit_server(server_id){
              var index = layer.open({
                  type: 2,
                  title: "编辑服务器信息",
                  scrollbar: false,
                  area: ['350px', '350px'],
                  shadeClose: true,
                  shift: 5,
                  moveOut: true,
                  content: ['/installation/server/edit/' + server_id,'no'],
                  end : function(){
                      window.location.reload();
                    }
                });
            }
    </script>

  </body>
</html>